name: gistagum
services:
- name: web
  github:
    repo: kennethkeeen/GISONETAGUMVISION
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: gistagum.settings
  - key: DEBUG
    value: "false"
  - key: DJANGO_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: ALLOWED_HOSTS
    scope: RUN_TIME
    type: SECRET
  - key: CSRF_TRUSTED_ORIGINS
    scope: RUN_TIME
    type: SECRET
  health_check:
    http_path: /
  routes:
  - path: /

