# Generated by Django 5.2.1 on 2025-05-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0005_projectcost_projectprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='photos',
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projeng.projectprogress')),
            ],
        ),
    ]
