# Generated by Django 5.2.1 on 2025-10-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='geometry',
        ),
    ]
