# Generated by Django 5.2.1 on 2025-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0013_barangaymetadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='zone_type',
            field=models.CharField(blank=True, help_text='Zoning classification at project location (R-1, R-2, C-1, I-2, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='zone_validated',
            field=models.BooleanField(default=False, help_text='Whether zone has been validated against official zoning'),
        ),
        migrations.CreateModel(
            name='ZoningZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('R-1', 'Low Density Residential Zone'), ('R-2', 'Medium Density Residential Zone'), ('R-3', 'High Density Residential Zone'), ('SHZ', 'Socialized Housing Zone'), ('C-1', 'Major Commercial Zone'), ('C-2', 'Minor Commercial Zone'), ('I-1', 'Heavy Industrial Zone'), ('I-2', 'Light and Medium Industrial Zone'), ('AGRO', 'Agro-Industrial Zone'), ('INS-1', 'Institutional Zone'), ('PARKS', 'Parks & Playgrounds/Open Spaces'), ('AGRICULTURAL', 'Agricultural Zone'), ('ECO-TOURISM', 'Eco-tourism Zone'), ('SPECIAL', 'Special Use Zone')], db_index=True, help_text='Type of zoning classification', max_length=20)),
                ('barangay', models.CharField(db_index=True, help_text='Barangay name', max_length=255)),
                ('location_description', models.TextField(help_text='Specific locations: subdivisions, roads, sites')),
                ('keywords', models.JSONField(default=list, help_text='Keywords for matching (subdivision names, road names, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this zone is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoning Zone',
                'verbose_name_plural': 'Zoning Zones',
                'ordering': ['barangay', 'zone_type'],
                'indexes': [models.Index(fields=['barangay', 'zone_type'], name='projeng_zon_baranga_8c8025_idx'), models.Index(fields=['is_active'], name='projeng_zon_is_acti_1819c4_idx')],
            },
        ),
    ]
