# Generated by Django 5.2.1 on 2025-11-11 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0014_add_zoning_zone_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='justification',
            field=models.TextField(blank=True, help_text='Justification for the progress increase (required for increases >10%)', null=True),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='description',
            field=models.TextField(help_text='Detailed description of progress made and work completed'),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the milestone/deliverable', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this milestone represents', null=True)),
                ('target_date', models.DateField(help_text='Expected completion date for this milestone')),
                ('completion_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this milestone has been completed')),
                ('estimated_progress_contribution', models.IntegerField(default=0, help_text='Estimated percentage of project completion this milestone represents (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projeng.project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['target_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this progress update to a specific milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to='projeng.projectmilestone'),
        ),
    ]
