# Generated by Django 5.2.1 on 2025-11-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0015_projectprogress_justification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Name of criteria configuration', max_length=100, unique=True)),
                ('weight_zoning', models.FloatField(default=0.3, help_text='Weight for zoning compliance (0-1)')),
                ('weight_flood_risk', models.FloatField(default=0.25, help_text='Weight for flood risk (0-1)')),
                ('weight_infrastructure', models.FloatField(default=0.2, help_text='Weight for infrastructure access (0-1)')),
                ('weight_elevation', models.FloatField(default=0.15, help_text='Weight for elevation suitability (0-1)')),
                ('weight_economic', models.FloatField(default=0.05, help_text='Weight for economic alignment (0-1)')),
                ('weight_population', models.FloatField(default=0.05, help_text='Weight for population density (0-1)')),
                ('project_type', models.CharField(choices=[('all', 'All Project Types'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('infrastructure', 'Infrastructure'), ('institutional', 'Institutional')], default='all', help_text='Project type this criteria applies to', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters for scoring (thresholds, ranges, etc.)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suitability Criteria',
                'verbose_name_plural': 'Suitability Criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandSuitabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='Overall suitability score (0-100)')),
                ('suitability_category', models.CharField(choices=[('highly_suitable', 'Highly Suitable (80-100)'), ('suitable', 'Suitable (60-79)'), ('moderately_suitable', 'Moderately Suitable (40-59)'), ('marginally_suitable', 'Marginally Suitable (20-39)'), ('not_suitable', 'Not Suitable (0-19)')], help_text='Suitability category based on score', max_length=30)),
                ('zoning_compliance_score', models.FloatField(help_text='Zoning compliance score (0-100)')),
                ('flood_risk_score', models.FloatField(help_text='Flood risk assessment score (0-100, higher = less risk)')),
                ('infrastructure_access_score', models.FloatField(help_text='Infrastructure access score (0-100)')),
                ('elevation_suitability_score', models.FloatField(help_text='Elevation suitability score (0-100)')),
                ('economic_alignment_score', models.FloatField(help_text='Economic zone alignment score (0-100)')),
                ('population_density_score', models.FloatField(help_text='Population density appropriateness score (0-100)')),
                ('has_flood_risk', models.BooleanField(default=False)),
                ('has_slope_risk', models.BooleanField(default=False)),
                ('has_zoning_conflict', models.BooleanField(default=False)),
                ('has_infrastructure_gap', models.BooleanField(default=False)),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations for improving suitability')),
                ('constraints', models.JSONField(default=list, help_text='List of constraints or limitations')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_version', models.CharField(default='1.0', help_text='Version of analysis algorithm used', max_length=20)),
                ('project', models.OneToOneField(help_text='Project being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='suitability_analysis', to='projeng.project')),
            ],
            options={
                'verbose_name': 'Land Suitability Analysis',
                'verbose_name_plural': 'Land Suitability Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
