# Generated by Django 5.2.1 on 2025-11-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0017_projecttype_zonealloweduse_zonerecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Type of project (e.g., Apartment Building, Hospital, Road)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projeng.projecttype'),
        ),
    ]
