# Generated by Django 5.2.1 on 2025-11-14 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0019_populate_project_types_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpatialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(help_text='Barangay name (geographic zone)', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this assignment was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('priority', models.IntegerField(default=1, help_text='Priority level (1 = primary, 2 = secondary, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who created this assignment (typically Head Engineer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spatial_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User (engineer) assigned to this geographic zone', on_delete=django.db.models.deletion.CASCADE, related_name='spatial_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Spatial Assignment',
                'verbose_name_plural': 'User Spatial Assignments',
                'ordering': ['user', 'barangay'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='projeng_use_user_id_a2d9b0_idx'), models.Index(fields=['barangay', 'is_active'], name='projeng_use_baranga_4c8edc_idx')],
                'unique_together': {('user', 'barangay')},
            },
        ),
    ]
