# Generated by Django 5.2.1 on 2025-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0020_userspatialassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoningzone',
            name='zone_type',
            field=models.CharField(choices=[('R-1', 'Low Density Residential Zone'), ('R-2', 'Medium Density Residential Zone'), ('R-3', 'High Density Residential Zone'), ('SHZ', 'Socialized Housing Zone'), ('C-1', 'Major Commercial Zone'), ('C-2', 'Minor Commercial Zone'), ('I-1', 'Heavy Industrial Zone'), ('I-2', 'Light and Medium Industrial Zone'), ('AGRO', 'Agro-Industrial Zone'), ('INS-1', 'Institutional Zone'), ('PARKS', 'Parks & Playgrounds/Open Spaces'), ('AGRICULTURAL', 'Agricultural Zone / SAFDZ'), ('ECO-TOURISM', 'Eco-tourism Zone'), ('SPECIAL', 'Special Use Zone'), ('COASTAL', 'Coastal Zone'), ('RECLAMATION', 'Reclamation Proposed Zone'), ('CEMETERY', 'Cemetery / Memorial Park Zone')], db_index=True, help_text='Type of zoning classification', max_length=20),
        ),
    ]
