# Generated by Django 5.2.1 on 2025-11-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0021_alter_zoningzone_zone_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringAlgorithmComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_projects', models.IntegerField(help_text='Total number of projects analyzed')),
                ('valid_projects', models.IntegerField(help_text='Projects with valid coordinates')),
                ('admin_silhouette', models.FloatField(blank=True, null=True)),
                ('admin_zas', models.FloatField(blank=True, null=True)),
                ('admin_calinski', models.FloatField(blank=True, null=True)),
                ('admin_davies', models.FloatField(blank=True, null=True)),
                ('admin_execution_time', models.FloatField(blank=True, null=True)),
                ('admin_cluster_count', models.IntegerField(blank=True, null=True)),
                ('kmeans_silhouette', models.FloatField(blank=True, null=True)),
                ('kmeans_zas', models.FloatField(blank=True, null=True)),
                ('kmeans_calinski', models.FloatField(blank=True, null=True)),
                ('kmeans_davies', models.FloatField(blank=True, null=True)),
                ('kmeans_execution_time', models.FloatField(blank=True, null=True)),
                ('kmeans_cluster_count', models.IntegerField(blank=True, null=True)),
                ('dbscan_silhouette', models.FloatField(blank=True, null=True)),
                ('dbscan_zas', models.FloatField(blank=True, null=True)),
                ('dbscan_calinski', models.FloatField(blank=True, null=True)),
                ('dbscan_davies', models.FloatField(blank=True, null=True)),
                ('dbscan_execution_time', models.FloatField(blank=True, null=True)),
                ('dbscan_cluster_count', models.IntegerField(blank=True, null=True)),
                ('dbscan_noise_count', models.IntegerField(blank=True, null=True)),
                ('hierarchical_silhouette', models.FloatField(blank=True, null=True)),
                ('hierarchical_zas', models.FloatField(blank=True, null=True)),
                ('hierarchical_calinski', models.FloatField(blank=True, null=True)),
                ('hierarchical_davies', models.FloatField(blank=True, null=True)),
                ('hierarchical_execution_time', models.FloatField(blank=True, null=True)),
                ('hierarchical_cluster_count', models.IntegerField(blank=True, null=True)),
                ('best_algorithm', models.CharField(help_text='Best performing algorithm', max_length=50)),
            ],
            options={
                'verbose_name': 'Clustering Algorithm Comparison',
                'verbose_name_plural': 'Clustering Algorithm Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='zoningzone',
            name='zone_type',
            field=models.CharField(choices=[('R-1', 'Low Density Residential Zone'), ('R-2', 'Medium Density Residential Zone'), ('R-3', 'High Density Residential Zone'), ('SHZ', 'Socialized Housing Zone'), ('C-1', 'Major Commercial Zone'), ('C-2', 'Minor Commercial Zone'), ('I-1', 'Heavy Industrial Zone'), ('I-2', 'Light and Medium Industrial Zone'), ('AGRO', 'Agro-Industrial Zone'), ('INS-1', 'Institutional Zone'), ('PARKS', 'Parks & Playgrounds/Open Spaces'), ('AGRICULTURAL', 'Agricultural Zone / SAFDZ'), ('ECO-TOURISM', 'Eco-tourism Zone'), ('SPECIAL', 'Special Use Zone')], db_index=True, help_text='Type of zoning classification', max_length=20),
        ),
    ]
