# Generated by Django 5.2.1 on 2026-01-22 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0022_clusteringalgorithmcomparison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Requested budget increase amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reason', models.TextField(help_text='Justification / assessment for requesting additional budget')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved budget increase amount (can be different from requested)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('decision_notes', models.TextField(blank=True, help_text='Notes/reason for approval or rejection', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='projeng.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_request_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('budget_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projeng.budgetrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projeng.budgetrequest')),
            ],
            options={
                'verbose_name_plural': 'Budget Request Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['project', 'status'], name='projeng_bud_project_e3a61a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetrequest',
            index=models.Index(fields=['status', 'created_at'], name='projeng_bud_status_1be1d2_idx'),
        ),
    ]
