# Generated by Django 5.2.1 on 2026-02-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeng', '0027_remove_project_purok_alter_projecttype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
