# Generated by Django 5.2.1 on 2025-05-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_project_barangay_project_end_date_project_prn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Project progress in percentage (0-100)', null=True),
        ),
    ]
